--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/PvPShop
build-by-default: true
branches:
- PM4
projects:
  PvPShop:
    path: ""
    icon: icon-pvpshop.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
        branch: "4.0"
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.1
        branch: "master"
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
        branch: "master"
    lint:
      phpstan: false
...
